apiVersion: v1
kind: ServiceAccount
metadata:
  name: testing9
  namespace: team1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing9
  namespace: team1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing9
      version: v1
  template:
    metadata:
      labels:
        app: testing9
        version: v1
    spec:
      serviceAccountName: testing9
      containers:
      - image: docker.io/asayahtest/testing9
        imagePullPolicy: IfNotPresent
        name: testing9
        ports:
        - containerPort: 8080