---
apiVersion: v1
kind: Service
metadata:
  name: testing9
  namespace: team1
  labels:
    app: testing9
    service: testing9
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: testing9